#define USER_EMAIL "nayantha2003@gmail.com"
#define USER_PASSWORD "Lancer2003"
#define API_KEY "AIzaSyC-Z0erl0XUtY4jlESjVVgp5nCeVK7upbU"
#define DATABASE_URL "https://sosamala-default-rtdb.asia-southeast1.firebasedatabase.app/"
#define FIREBASE_PROJECT_ID "sosamala"